version: '3.4'

services:
  hashkorea-blazor:
    image: ${DOCKER_REGISTRY-}hashkoreablazor
    env_file: .env
    container_name: hashkorea-blazor
    build:
      context: .
      dockerfile: HashKorea-Blazor/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=${AWS_SERVER};Port=3306;Database=${AWS_DATABASE};User=${AWS_USER};Password=${AWS_PASSWORD};
      - NODE_ENV=development
      # MSSQL
      # - ConnectionStrings__DefaultConnection=Server=hashkorea.database;Database=HashKorea;User Id=sa;Password=${SA_PASSWORD:-YourStrong@Passw0rd1};TrustServerCertificate=True;Encrypt=False;
    volumes:
      # - ./init-scripts:/docker-entrypoint-initdb.d
      - ./uploads:/app/uploads
      - ~/.aws:/root/.aws:ro
    user: "${UID}:${GID}"
  hashkorea.cache:
    image: redis:latest
    container_name: hashkorea.cache
    restart: always
    ports:
      - '6379:6379'